version: '3.8'

services:
  mercadoDB-service:
    image: postgres:15.3
    container_name: mercadoDB-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mercadoDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - mercadoDB-service
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./images:/usr/share/nginx/html/images
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - upload-server

  upload-server:
    build: ./upload-server
    ports:
      - 4000:4000
    environment:
      - UPLOAD_SECRET=${UPLOAD_SECRET}
    volumes:
      - ./upload-server:/app
      - /app/node_modules           # Esto evita que montes tu carpeta vacía encima de node_modules
      - ./images:/store/images


volumes:
  pgadmin-data:
    driver: local

networks:
  app-network:
    driver: bridge
